import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { globalWatcher } from '@/lib/fs/watcher';

// Start watching clawd directory
if (process.env.NODE_ENV === 'development') {
  globalWatcher.start([
    'clawd/tasks',
    'clawd/approvals',
    'clawd/projects',
    'clawd/people',
    'clawd/cron',
    'clawd/memory',
  ]);
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
